### ISSUE TITLE
Provide an executable script

### ISSUE THREAD

**Issue by vadmbertr** [meom-group/jaxparrow#13]
- how do we handle inputs/outputs?
  - use as arg to the script a yaml/json conf file describing how and where input data should be read and output data should be stored
- should args include methods HP?

**Comment by lesommer** [comment]
a natural solution could be to prepare a script for computing cyclogeostriophic current from NEMO output, folllowing the same API and assumptions as CDFTOOLS : https://github.com/meom-group/CDFTOOLS
