### ISSUE TITLE
[meom code clinic] tests

### ISSUE THREAD

**Issue by rcaneill** [meom-group/jaxparrow#70]
This issue is open for the MEOM internal code clinic / review process

**Comment by rcaneill** [comment]
### tests

- [ ] **The package has tests:**
  - [ ] Tests cover essential functions of the package and a reasonable range of inputs and conditions.
- [ ] **Continuous Integration:** Has continuous integration setup (We suggest using Github actions but any CI platform is acceptable for review)

**Comment by lesommer** [comment]
See issues #79

**Comment by lesommer** [comment]
Now closing code review.
