### ISSUE TITLE
[meom code clinic] Documentation

### ISSUE THREAD

**Issue by rcaneill** [meom-group/jaxparrow#71]
This issue is open for the MEOM internal code clinic / review process

**Comment by rcaneill** [comment]
### Documentation

- [ ] **Vignette(s)** / **Example usage:** demonstrating major functionality (ideally to solve real-world analysis problems).
- [ ] **Function Documentation:** for functions used in the examples.

**Comment by lesommer** [comment]
See #75 and #80

**Comment by lesommer** [comment]
Now closing the issue
