### ISSUE TITLE
[meom code clinic] README

### ISSUE THREAD

**Issue by rcaneill** [meom-group/jaxparrow#72]
This issue is open for the MEOM internal code clinic / review process

**Comment by rcaneill** [comment]
The README should include:

- [ ] The package name
- [ ] Short description of package goals.
- [ ] Package installation instructions
    - [ ] Brief demonstration of package usage (as it makes sense - links to vignettes could also suffice here if package description is clear)
- [ ] Link to your documentation website.
- [ ] If applicable, how the package compares to other similar packages and/or how it relates to other packages in the scientific ecosystem.
- [ ] Citation information

**Comment by lesommer** [comment]
[revieed by @lesommer  @weisslisa @HugoJacq ]

Check list : 
- name : ok 
- description : ok 
- installation : ok 
- Link to documentation : missing 
- Other package : missing 
- Citation information : missing 

Other improvements : 
 - a short visual demo with a code snippet

**Comment by lesommer** [comment]
Closing the review issu

**Comment by lesommer** [comment]
See above issues.
