### ISSUE TITLE
Add link to documentation

### ISSUE THREAD

**Issue by HugoJacq** [meom-group/jaxparrow#74]
Link is missing in the README

**Comment by rcaneill** [comment]
https://github.com/meom-group/jaxparrow/blob/7c2bc7b55d038a67649220fd66b3f155dc067698/README.md?plain=1#L6

**Comment by rcaneill** [comment]
doc link is in the badge, but less visible than having a text link

**Comment by vadmbertr** [comment]
closed in #83
