### ISSUE TITLE
wrong doi in citation file

### ISSUE THREAD

**Issue by AnthonyBosse** [meom-group/jaxparrow#86]
Hi,
first thank you for the great work! It really timed well because I had just noticed the divergence of classic iterative approach to solve cyclogeostrophy and I could not think of a satisfying solution. A colleague told me that he saw your work at EGU 2024, and I then used your package.
I am now planning to use it in a paper and had a look at the citation file. It seems that doi is wrong (doi: 10.5281/zenodo.8010997), it shoud be (10.5281/zenodo.13886071), if I am correct?
Best regards,
Anthony

**Comment by vadmbertr** [comment]
Hi Anthony,

Sorry for the late reply...
Yes you're absolutely right! I'll fixed it in the citation file, thanks.
Glad you used the package!

Best,
Vadim

**Comment by vadmbertr** [comment]
Closed by #87
